### ISSUE TITLE
Introduction Page

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/digital-platform#107]
We need to navigate from the advert on the current website to the application service prototype.  
This text is for the first page the user sees when they have registered/logged in

PLACEHOLDER for TEXT

**Comment by ClaireTroughtonJAC** [comment]
![User Journey.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc460f394f9c300114a167a/125516c66e82c728ace21e0d46dd879f31c2a9a69afbb146bd1fbcd6395428792c07b7692ac7b62bee127d51585f1ca9440e5c17fcf88e7aa4e53577895819f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b98b44c0e83e25e2828c462c53.JPG)

**Comment by ClaireTroughtonJAC** [comment]
Alpha team have mapped out journey from website.  

Questions are:  

Will a user be logged out after a period of inactivity?  
Will the user need to login again after validation?

**Comment by tatyree** [comment]
For logout after inactivity, they can be. 

Technical implementation details here:

https://firebase.google.com/docs/auth/web/auth-state-persistence#modifying_the_auth_state_persistence

For login after validation, they *should* already have a session when the click the link and so *should not* need to re-login.  However, this may not always work as expected due to the variety of ways different browsers respond.

**Comment by JonSJAC** [comment]
Please amend:
Vacancy to all lower case.
Please can the sub heading be removed (Introduction)
Is there a need for the introduction page?

**Comment by JonSJAC** [comment]
Remove the introduction navigation.
Place exercise name in favour of vacancy in the title.

**Comment by ollietreend** [comment]
@ClaireTroughtonJAC please define so this is ready for dev
