### ISSUE TITLE
Experience page

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#127]
Please change page title to Experience, deleting the word "Your".

For all year boxes in the "Experience page", please can they start from the year 1960, as opposed to 0.

2) Re the list of activities:- can we change 'other' to 'any other activity that, in the relevant decision-maker's opinion, is of a broadly similar nature to those listed above'.

3) Can you remove the following questions:
Have you had any work published? and
Are you a member of any legal associations?.

**Comment by JonSJAC** [comment]
Please check logic of selecting radio buttons for judicial appointment. More questions seemed to appear only after leaving the question and returning to it.

Change question, how many days have you sat in this appointment, to If fee-paid, how many days have you sat in this appointment.

Gaps in employment options appears when selecting Government Legal Service or Crown Prosecution Service options, please can this only appear is selecting career break.

Which Circuit do you work on? Please change south east to South East and North eastern to North Eastern

Under legal associations. Please change text box label to: Name of legal association

**Comment by CbarkerJAC** [comment]
The policy team have reviewed this page and would like to advise the following amendments:

**1)** If the answer to 'Have you had any gaps in employment since you qualified?' is 'YES'. Can the next question be:
Did you undertake law related activities for at least 20% of this time in any given year? YES/NO
If the answer is 'YES' then the list appears.  

We advise this question is added because law related activities will only count towards their eligibility (during a gap in their employment) if they were completing this for at least 20% of their employment gap time in any given year. 

**2)** Re the list of activities:- can we change 'other' to 'any other activity that, in the relevant decision-maker's opinion, is of a broadly similar nature to those listed above'. 

We advise this question is changed because we have to be more specific and we want to stick to the wording as used in the statute so there can be no misunderstanding or misinterpretation. 

**3)** Can you remove the following questions:
Have you had any work published?  and
Are you a member of any legal associations?

We advise the removal of these questions because we (in the policy team) did some work on the value of asking these questions and concluded there was no value in asking them. We agreed that we would remove these questions from the app form.

**Comment by CbarkerJAC** [comment]
In JOn's comment where he suggests: Change question, how many days have you sat in this appointment, to If fee-paid, how many days have you sat in this appointment.

We , in policy,  suggest we change the question to 'Have you sat for 30 days or more?
We believe this will suit for both FP and Salaried judicial applicants.

**Comment by ollietreend** [comment]
I've removed 'Your' from the page title, and removed the 'Published Work' and 'Legal Associations' sections from the form. These are available in PR: https://github.com/JudicialAppointmentsCommission/application-form/pull/88

However, I'm pushing back on changing the label **"Other"** to **"any other activity that, in the relevant decision-maker's opinion, is of a broadly similar nature to those listed above"**.

This is not good for the user experience. It's 20 words instead of 1 – why the extra complication? Additionally, how is a user supposed to know what the "relevant decision-maker's opinion" is? Who even _is_ the "relevant decision-maker"?

I'm blocking this card until we can resolve this.

**Comment by ClaireTroughtonJAC** [comment]
@ollietreend @LaurieJohnston I understand the frustration about this but "Other" is not in statute - its actually that blurb direct from statue hence the concern simply saying "Other". Is there a way we can show the full text when you click other?  Or should we try and link to guidance for the MVP.  Please can you consider with Kas and Nora today.

**Comment by kaspatel** [comment]
@ClaireTroughtonJAC  Nora and I discussed and have agreed: other activity that may be considered law-related
