### ISSUE TITLE
Preferences editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#134]
Change left hand navigation to: Work pattern 
Change page title to: Work pattern preferences

Change question to: Are you interested in salaried part-time working?

**Comment by CbarkerJAC** [comment]
The policy team have reviewed this page and would like to advise the following amendments:

1) we agree with the request to change the question to:
Are you interested in salaried part-time working? 

2) Remove the 'Blocks of weeks' options from the sitting pattern options. 

We ask for this amendment because the VR states 'Salaried part time working can only be accommodated by working full weeks and in blocks of periods of a minimum of at least 6 to 8 weeks.' This means that the only SPTW option is the 6 to 8 weeks option. There is no other blocks of weeks options available to choose from.
