### ISSUE TITLE
Reasonable Adjustments

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#28]
The candidate needs to input their Reasonable adjustment with a Yes/ No box. (User research needed can be worked on later, wording to be agreed by Nora. 
Candidates as a minimum need to explain there reasonable adjustment, i.e special chair, wheelchair access. Needs to be downloadable for the selection time to arrange candidates wishes

**Comment by LaurieJohnston** [comment]
We need to decide whether to keep this question under personal details - would it fit better elsewhere?

Your health

By law we might have to make changes known as ‘reasonable adjustments’ to anything that puts you at a ‘substantial disadvantage’ compared to people without a disability or health condition.

Q1 Do you have a disability or health condition that might affect your ability to sit an online test or attend an interview or role play?
<Radio buttons> 
Yes <show text 1a>
No

Required field
Validation error: Select yes or no

Text 1a - Call us on 020 3334 0123 to explain how your condition affects you and what help you think you’ll need

**Comment by ollietreend** [comment]
Uploading PDF of wireframe here so that we can throw away the paper. @LaurieJohnston is this still the correct wireframe to use?

[Reasonable adjustments.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2282fc0cd4a70013bf9da7/125516c66e82c728ace21e0d46da919b308d8da88de5ba03a559fa813a522a762710b0693cc7f33ab0487e021b4d44be440b5e44aaf98e2bf4b33926890f0becd63c5d27cf3a12a8aa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4a3f160c1b88fe5b3ca99b5985.pdf)

**Comment by LaurieJohnston** [comment]
Yes, correct wireframe except no text box at the end, just this wording if user selects yes - Email reasonableadjustments@jac.gsi.gov.uk or call 020 3334 0123 to explain how your condition affects you and what help you think you’ll need
