### ISSUE TITLE
Candidate Diversity

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/digital-platform#45]
# Background
As a statistician
I want candidates to complete their diversity information
so that it can be collected at various stages of the exercise.

**The candidate is under no obligation to complete diversity
questions.** So if they choose not to complete ideally these fields
could be skipped.

We would like this to be displayed as the last section of the
application.

## Done When
The following subsections and fields are available and save to the
database:

### [Section] Sharing my diversity data (radio button group)
- [x] You may share my diversity data with the MoJ, Judicial Office
and HMCTS (for monitoring purposes only)
- [ ] DO NOT share my diversity data

### [Section] What is your professional background? Select all that apply.
- [ ] Solicitor
- [ ] Barrister
- [ ] CILEx
- [ ] I prefer not to answer this question
- [ ] Other (please specify)

### [Section] What is your current legal role? If you currently hold multiple roles, select all that apply.
- [ ]  Academic
- [ ]  Barrister
- [ ]  Fee-paid court judge
- [ ]  Fee-paid tribunal judge
- [ ]  Fellow of CILEx
- [ ]  Other fee-paid judicial office holder
- [ ]  Other salaried judicial office holder
- [ ]  Salaried court judge
- [ ]  Salaried tribunal judge
- [ ]  Solicitor
- [ ]  I prefer not to answer this question
- [ ]  Other (please specify)

### [Section] Do you hold, or have you held in the past, a fee-paid judicial role?
- [ ] Fee-paid court post
- [ ] Fee-paid tribunal post
- [ ] Other fee-paid judicial office holder
- [ ] I have not previously held a fee-paid role
- [ ] I prefer not to answer this question

#### [Subsection] White
- [ ] English, Welsh, Scottish, Northern Ireland, British
- [ ] Irish
- [ ] Gypsy or Irish Traveller
- [ ] Any other White background

#### [Subsection] Mixed/multiple ethnic backgrounds
- [ ] White and Black Caribbean
- [ ] White and Black African
- [ ] White and Asian

#### [Subsection] Any other mixed/multiple ethinic background
- [ ] Asian/Asian British
- [ ] Indian
- [ ] Pakistani
- [ ] Bangladeshi
- [ ] Chinese
- [ ] Any other Asian background

#### [Subsection]  Black/African/Caribbean/Black British
- [ ] African
- [ ] Caribbean
- [ ] Any other Black/African/Caribbean background

#### [Subsection] Other ethnic group
- [ ] Arab
- [ ] Other

- [ ] I prefer not to answer this question

### [Section]What is your sex?
- [ ] Male
- [ ] Female
- [ ] Other (e.g. Transgender)
- [ ] I prefer not to answer this question

### [Section]  Is your gender identity the same as the sex you were
assigned at birth?
- [ ] Yes
- [ ] No
- [ ] I prefer not to answer this question

### [Section] How would you describe your sexual orientation?
- [ ] Bisexual
- [ ] Gay man
- [ ] Gay woman/ lesbian
- [ ] Heterosexual/ straight
- [ ] Other
- [ ] I prefer not to answer this question

### [Section]  Do you have a disability, as defined by the Equality Act 2010?
- [x] Yes
- [ ] No
- [ ] I prefer not to answer this question

### [Section]  What is your religion or belief?
- [ ] Atheist
- [ ] Buddhist
- [ ] Christian
- [ ] Hindu
- [ ] Jewish
- [ ] Muslim
- [ ] No religion
- [ ] Sikh
- [ ] Other (please specify) (Text Box)
- [ ] I prefer not to answer this question

**Comment by tatyree** [comment]
@ClaireTroughtonJAC 
I'm going to move this one down in the backlog so we can discuss it.  Writing it out in the ticket, it feels like we've got a lot of duplication.  Can we not amalgamate the application form data (work history, legal experience, et al) with the specific diversity questions (ethnicity, gender, orientation, etc) to form the basis of the report **without** asking the candidates to repeat themselves?

**Comment by ClaireTroughtonJAC** [comment]
We have retained l

**Comment by ClaireTroughtonJAC** [comment]
@tatyree @ollietreend further to your comments about this we have spoken with Nora and she has made the point that the diversity information is collected for another purpose and shared with partners so whilst we might be duplicating information it is because it cannot be attributable to the candidate.  

we need this diversity information in as set out above (we are finalising the ticket at the time of writing this) for this first exercise.  To consider how we will amalgamate the data requires more time than we have, however Alpha team will consider this further and liaise with the appropriate team.  

I have reviewed GDS but there is no information on the service design about this.  Having chatted to Laurie we would normally expect this information to be collected at the end of the application.  

So order should be 

Nationality 
Personal Details
Career History
Application Specific answers
Character declaration
Diversity

**Comment by ollietreend** [comment]
# Background 
As a statistician 
I want candidates to complete their diversity information
so that it can be collected at various stages of the exercise.  

**The candidate is under no obligation to complete diversity questions.** So if they choose not to complete ideally these fields could be skipped.  

We would like this to be displayed as the last section of the application.  

## Done When
The following subsections and fields are available and save to the database:

### Sharing my diversity data (radio button group)
  - You may share my diversity data with the MoJ, Judicial Office and HMCTS (for monitoring purposes only)
  - DO NOT share my diversity data

The professional and judicial below fields will be pre-populated from the pick lists from job roles the Career History Section:  

### Q1. What is your professional background? Select all that apply.

 - [ ]  Solicitor
 - [ ] Barrister
 - [ ] CILEx
- [ ] I prefer not to answer this question
- [ ] Other (please specify)

### Q2. What is your current legal role? If you currently hold multiple roles, select all that apply.

- [ ]  Academic
- [ ]  Barrister
- [ ]  Fee-paid court judge
- [ ]  Fee-paid tribunal judge
- [ ]  Fellow of CILEx
- [ ]  Other fee-paid judicial office holder
- [ ]  Other salaried judicial office holder
- [ ]  Salaried court judge
- [ ]  Salaried tribunal judge
- [ ]  Solicitor
- [ ]  I prefer not to answer this question
- [ ]  Other (please specify)

### Q3. Do you hold, or have you held in the past, a fee-paid judicial role?

- [ ] Fee-paid court post
- [ ] Fee-paid tribunal post
- [ ] Other fee-paid judicial office holder
- [ ] I have not previously held a fee-paid role
- [ ] I prefer not to answer this question

The following are additional diversity fields not captured elsewhere in the application form.

### Q4. Ethnicity

### Q4.  What is your ethnic group?
 - [ ] White  
- [ ] English, Welsh, Scottish, Northern Ireland, British 
- [ ] Irish 
- [ ] Gypsy or Irish Traveller 
- [ ] Any other White background 

- [ ] Mixed/multiple ethnic backgrounds 
- [ ] White and Black Caribbean 
- [ ] White and Black African 
- [ ] White and Asian 

- [ ] Any other mixed/multiple ethnic background 
- [ ] Asian/Asian British
- [ ] Indian 
- [ ] Pakistani 
- [ ] Bangladeshi 
- [ ] Chinese
 
- [ ] Any other Asian background 
 
- [ ] Black/African/Caribbean/Black British 
- [ ] African 
- [ ] Caribbean 
- [ ] Any other Black/African/Caribbean background 

- [ ] Other ethnic group 
- [ ] Arab 
 
- [ ] Other
- [ ] I prefer not to answer this question

- [ ] Sex
- [ ] What is your sex?
		- [ ] Male
		- [ ] Female
		- [ ] Other (e.g. Transgender)
		- [ ] I prefer not to answer this question

- [ ] Is your gender identity the same as the sex you were assigned at birth?
	- [ ] Yes
	- [ ] No
	- [ ] I prefer not to answer this question

- [ ] Sexual Orientation
- [ ] How would you describe your sexual orientation?
	- [ ] Bisexual
	- [ ] Gay man
	- [ ] Gay woman/ lesbian
	- [ ] Heterosexual/ straight
	- [ ] Other
	- [ ] I prefer not to answer this question

- [ ] Disability
- [ ]  Do you have a disability, as defined by the Equality Act 2010?
	- [ ] Yes
	- [ ] No
	- [ ] I prefer not to answer this question

- [ ]  Religion or Belief
- [ ] Below is a list of religions commonly found in Britain, in alphabetical order. 
- [ ] What is your religion or belief?
	- [ ] Atheist
	- [ ] Buddhist
	- [ ] Christian
	- [ ] Hindu
	- [ ] Jewish
	- [ ] Muslim
	- [ ] No religion
	- [ ] Sikh
	- [ ] Other (please specify) (Text Box)
	- [ ] I prefer not to answer this question

**Comment by tatyree** [comment]
After discussing with @ollietreend and working through the wireframes, I have cleaned up the ticket a bit to make the sections and subsections clearer in the description.

**Comment by tatyree** [comment]
Attaching the rough-draft wireframes.  These describe the structure.  Please refer to the description for the questions.  

[Scanned_20190226-1230.pdf](https://github.com/JudicialAppointmentsCommission/digital-platform/files/2905401/Scanned_20190226-1230.pdf)

**Comment by NoraJAC** [comment]
Updated and tidied wording of questions and intro text is now ready: https://docs.google.com/document/d/1sHrhkWldpi7hxKBVl_A4X9EgM7lma-Bwboqjdp8xPl0/edit

No change to wire-frames . Just some introductory text added at top.

**Comment by CbarkerJAC** [comment]
The list of options for each section should be consistent all the way through e.g. alphabetical order. I have noted that the they are all in alpha order apart from the 'Ethnicity' and 'What is your sex sections'.
