### ISSUE TITLE
Your self assessment

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#97]
Requires JudicialAppointmentsCommission/application-form#41

### Additional Selection Criteria
<Insert link to guidance url to the information page where this is set out>

Q1 How do you meet this requirement? (Mandatory question)
[Text Box 250 words max]

### Authorisations
Q2: Do you currently have a Section 9(1) authorisation? (Mandatory question)
link guidance to information page
- [ ] Yes
- [ ] No
Radio Buttons

### Self Assessment
You may wish to refer to our guidance and the competency framework for this exercise before you complete this part of your application. 
[urls to competency framework and guidance- no link at the moment]

### Exercising Judgement
[Text Box 250 words max]

### Possessing and Building Knowledge
[Text Box 250 words max]

### Assimilating and Clarifying Information
[Text Box 250 words max]

### Working and Communicating with others
[Text Box 250 words max]

### Managing Work Effectively
[Text Box 250 words max]

**Comment by ollietreend** [comment]
Tone and wording of questions feels inconsistent here. For example when compared to the Qualifications page, which asks a question in each heading, whereas these headings are all labels.

**Comment by JonSJAC** [comment]
Please add

Leadership
[Text Box 250 words max]

**Comment by ollietreend** [comment]
I'm assigning this ticket to 'snagging' milestone to incorporate the missing leadership competency question outlined by @JonSJAC above

**Comment by CbarkerJAC** [comment]
The policy team have reviewed this page and would like to advise the following amendments:

**1)** Re ASC:- we would advise that you specify the the ASC here. We would like you to spell it out regardless of how long it is, but if that seriously offends you then a hyperlink to where it is spelt out in the info page would be great. Either way the policy team agreed (a better user experience was one of the factors) that it would be better if the candidate had sight of the ASC for this question.  

**2)** Re Authorisations:- amend the question to:
Do you currently have a Section 9(1) authorisation to sit in the Queen's Bench Division and/or the Administrative Court?

We advise you amend this question because 'it is required that the successful candidate must already be authorised or be suitable for authorisation upon appointment to act as a judge of the High Court under section 9(1) of the Senior Courts Act 1981 in the Queen’s Bench Division and the Administrative Court'. Amending this question will help us identify the candidates that already possess the relevant/required authorisations. The ones who do not will have to be assessed accordingly.
